# Generated by Django 4.2 on 2026-02-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_password',
            field=models.CharField(max_length=128),
        ),
    ]
